name: Deploy to SiteGround

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to SiteGround via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: ${{ secrets.FTP_PORT }}
          local-dir: "./"  # Adjust if needed
          server-dir: "/kohparenting.com/public_html/wp-content/themes/kohparenting/test/"
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/README.md
            **/libraries/**
            **/vendor/**