name: Deploy to SiteGround

on:
  push:
    branches:
      - main  # Change this if deploying from a different branch

jobs:
  deploy:
    name: Upload via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to SiteGround via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: sftp
          port: ${{ secrets.FTP_PORT }}
          local-dir: "./"  # Adjust if needed
          server-dir: "/public_html/"  # Change based on where your site is hosted
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/README.md